name: agentic-semantic-layer
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.4
  - pandas
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - networkx
  - sqlalchemy
  - sqlalchemy_schemadisplay
  - pygraphviz
  - scikit-learn
  - scipy
  - hdbscan
  - nltk
  - pip
  - pip:
      # - autogen-agentchat~=0.2 , to use the stable 0.2 version of autogen
      - pyautogen[all]
      - flaml==2.2.0
      - snowflake-connector-python